
name: test.yml

on: 
  push:
    paths:
    - 'test'

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Build Linux
      shell: bash
      run: |
        make -C test
